version: "3.9"
services:
    web:
        build: .
        ports:
            - "8000:80"
        environment:
            ASPNETCORE_ENVIRONMENT: "Development"
            ConnectionStrings__SqlConnection: "Server=db;Initial Catalog=Payments;User=sa;Password=2Secure*Password2"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"        
        environment:
            SA_PASSWORD: "2Secure*Password2"
            ACCEPT_EULA: "Y"
        ports:
          - 1433:1433